"""Format blast-radius impact reports for stdout and markdown."""
from __future__ import annotations


def _risk_label(blast_score: float, total_nodes: int) -> str:
    if total_nodes == 0:
        return "UNKNOWN"
    pct = (blast_score / total_nodes) * 100
    if blast_score >= 20 or pct >= 30:
        return "CRITICAL"
    if blast_score >= 10 or pct >= 15:
        return "HIGH"
    if blast_score >= 4 or pct >= 5:
        return "MEDIUM"
    return "LOW"


def format_stdout(
    file_id: str,
    blast: dict,
    total_nodes: int,
) -> str:
    d   = blast["direct_dependents"]
    t   = blast["transitive_dependents"]
    sc  = blast["blast_score"]
    risk = _risk_label(sc, total_nodes)

    lines = [
        f"Impact: {file_id}",
        f"Blast Score: {sc}  ({d} direct · {t} transitive)  [{risk}]",
        "",
    ]

    if blast["direct_ids"]:
        lines.append(f"Direct dependents ({d})")
        for nid in sorted(blast["direct_ids"]):
            lines.append(f"  {nid}")
        lines.append("")

    if blast["transitive_ids"]:
        lines.append(f"Transitive dependents ({t})")
        paths = blast["dep_paths"]
        for nid in sorted(blast["transitive_ids"]):
            path = paths.get(nid, [nid])
            chain = " → ".join(reversed(path)) if len(path) > 1 else nid
            lines.append(f"  {nid}  ← {chain}" if len(path) > 1 else f"  {nid}")
        lines.append("")

    if total_nodes:
        affected = d + t
        pct = round((affected / total_nodes) * 100, 1)
        lines.append(f"Risk: {risk} — affects {affected}/{total_nodes} files ({pct}% of codebase)")

    return "\n".join(lines)


def format_markdown(
    file_id: str,
    blast: dict,
    total_nodes: int,
) -> str:
    d    = blast["direct_dependents"]
    t    = blast["transitive_dependents"]
    sc   = blast["blast_score"]
    risk = _risk_label(sc, total_nodes)

    lines = [
        f"# Impact Report: `{file_id}`",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Blast Score | **{sc}** |",
        f"| Direct dependents | {d} |",
        f"| Transitive dependents | {t} |",
        f"| Risk | **{risk}** |",
        "",
    ]

    if blast["direct_ids"]:
        lines.append(f"## Direct dependents ({d})")
        lines.append("")
        for nid in sorted(blast["direct_ids"]):
            lines.append(f"- `{nid}`")
        lines.append("")

    if blast["transitive_ids"]:
        lines.append(f"## Transitive dependents ({t})")
        lines.append("")
        paths = blast["dep_paths"]
        for nid in sorted(blast["transitive_ids"]):
            path = paths.get(nid, [nid])
            chain = " → ".join(reversed(path)) if len(path) > 1 else ""
            suffix = f" ← `{chain}`" if chain else ""
            lines.append(f"- `{nid}`{suffix}")
        lines.append("")

    if total_nodes:
        affected = d + t
        pct = round((affected / total_nodes) * 100, 1)
        lines.append(f"## Summary")
        lines.append("")
        lines.append(
            f"Modifying `{file_id}` could affect **{affected}/{total_nodes}** files "
            f"(**{pct}%** of codebase). Risk level: **{risk}**."
        )
        lines.append("")
        lines.append(
            "_Generated by [blastradius](https://github.com/scheidydudes/blastradius)_"
        )

    return "\n".join(lines)
